services:
  api:
    build: .
    container_name: trade-crm-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Avoid overriding node_modules
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: trade_crm_db
    restart: always

  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trade_crm_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
